language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes ia32-libs ia32-libs-multiarch
  - npm install -g grunt-cli
